defaults:
- main
- _self_

gt_path: data/final/metadata.xlsx
pred_path: data/interim_predict/SABL/metadata.xlsx
# List of features: Cephalization, Artery, Heart, Kerley, Bronchus, Effusion, Bat, Infiltrate, Cuffing, Lungs
include_features: [Bat]
save_images: true
save_dir: data/final_vis/SABL/bat
